import CartProvider from "@/context/CartContext";
import "./globals.css";
import Navbar from '@/Components/Navbar'
import Footer from "@/Components/Footer";

export const metadata = {
  title: "E-commerce",
  description: "Generated by vivek",
  
};

export default function RootLayout({ children  }) {

  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar/>
            {children}
            <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}